name: PR activity
run-name: PR activity by ${{ github.actor }} 🚀
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
jobs:
  notify-opened-or-reopened:
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      (github.event.action == 'opened' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "${{ github.event.pull_request.title }}"
          content: "**${{ github.event.pull_request.title }}**\n${{ github.event.pull_request.commits }} commit(s): ${{ github.event.pull_request.changed_files }} changed file(s) with ${{ github.event.pull_request.additions }} addition(s) and ${{ github.event.pull_request.deletions }} deletion(s)"
