name: Job test
run-name: ${{ github.actor }} added new changes 🚀
on:
  push:
    branches:
      - main
      - feat/*
      - fix/*
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
  Notify-Discord:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Complex Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@${{ secrets.DISCORD_ME }}> and @here! ${{ github.job }}"
          title: "Pushed to ${{ github.repository }}"
          description: "Pushed ${{ github.repository }} on ${{ github.ref }}"
          color: 0x00dd00
      - name: Notify if fails
        uses: sarisia/actions-status-discord@v1
        if: failure() || cancelled()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "@here Hurry up!"
          description: "Puede que esto necesite de su atención"
