name: Job test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with: 
          cmd: install --frozen-lockfile --inmutable
      - name: Run app
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: start
